services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: acquiring
    networks:
      - acquiring_app_network
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: acquiring_container
    env_file:
      - .env
    networks:
      - acquiring_app_network
    depends_on:
      - db  # Приложение зависит от базы данных, но не ждет готовности
    ports:
      - "8080:8080"
    volumes:
      - ./internal:/internal  # Монтируем папку с хоста в контейнер (без него, не видит файл form.html)

  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    container_name: nginx_container
    depends_on:
      - app  # Nginx зависит от приложения
    ports:
      - "80:80"
      - "443:443"
    networks:
      - acquiring_app_network
    volumes:
      - ./ssl:/etc/nginx/ssl  # Монтируем локальную папку ./ssl в контейнер

networks:
  acquiring_app_network:
    external: true

volumes:
  db_data:
